### ISSUE TITLE
Lack of option to specify port

### ISSUE THREAD

**Issue by kristenkam** [ToeBee/ChangesetMD#12]
Defaults to port 5432. 

Have script default to port 5432 if a port is not specified at commandline.

Kristen

**Comment by pnorman** [comment]
Can this be done with the PGPORT env var?

**Comment by kristenkam** [comment]
Hi.

Yeah, the psycopg module's psycopg2 class has a connect method keyword to specify the port number. You can update the logic to parse the port number from command line if its specified.

**Comment by kristenkam** [comment]
done. wanna check it out?

https://github.com/kristenkam/ChangesetMD/commit/64cf77901cd4bbeb12a2586635590e974e36c8d1

**Comment by ToeBee** [comment]
Finally got around to merging this with some additional tweaks from @pnorman.
